CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    email       VARCHAR(160) NOT NULL UNIQUE,
    senha_hash  VARCHAR(100) NOT NULL,
    perfil      VARCHAR(20)  NOT NULL,
    criado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE produtos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku               VARCHAR(40)    NOT NULL UNIQUE,
    nome              VARCHAR(120)   NOT NULL,
    categoria         VARCHAR(30)    NOT NULL,
    unidade           VARCHAR(10)    NOT NULL,
    quantidade_atual  NUMERIC(14, 2) NOT NULL DEFAULT 0,
    estoque_minimo    NUMERIC(14, 2) NOT NULL DEFAULT 0,
    localizacao       VARCHAR(120),
    descricao         VARCHAR(500),
    atualizado_em     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE movimentacoes_estoque (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id    BIGINT         NOT NULL REFERENCES produtos (id) ON DELETE CASCADE,
    tipo          VARCHAR(10)    NOT NULL,
    quantidade    NUMERIC(14, 2) NOT NULL,
    saldo_apos    NUMERIC(14, 2) NOT NULL,
    motivo        VARCHAR(200),
    responsavel   VARCHAR(120),
    id_cliente    VARCHAR(36)    UNIQUE,
    ocorrido_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    registrado_em TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_mov_produto_data ON movimentacoes_estoque (produto_id, ocorrido_em);

CREATE TABLE colheitas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talhao                VARCHAR(60)    NOT NULL,
    cultura               VARCHAR(60)    NOT NULL,
    area_ha               NUMERIC(10, 2) NOT NULL,
    data_plantio          DATE           NOT NULL,
    previsao_colheita     DATE           NOT NULL,
    data_colheita         DATE,
    producao_estimada_kg  NUMERIC(14, 2),
    producao_real_kg      NUMERIC(14, 2),
    status                VARCHAR(20)    NOT NULL,
    produto_id            BIGINT REFERENCES produtos (id) ON DELETE SET NULL,
    observacoes           VARCHAR(500)
);

CREATE TABLE veiculos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacao       VARCHAR(30)    NOT NULL UNIQUE,
    modelo              VARCHAR(120)   NOT NULL,
    tipo                VARCHAR(20)    NOT NULL,
    ano                 INTEGER        NOT NULL,
    horimetro           NUMERIC(10, 1) NOT NULL DEFAULT 0,
    status              VARCHAR(20)    NOT NULL,
    proxima_manutencao  DATE,
    observacoes         VARCHAR(500)
);

CREATE TABLE dispositivos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(40)  NOT NULL UNIQUE,
    nome                VARCHAR(120) NOT NULL,
    tipo                VARCHAR(30)  NOT NULL,
    localizacao         VARCHAR(120),
    latitude            DOUBLE PRECISION,
    longitude           DOUBLE PRECISION,
    api_key_hash        VARCHAR(64)  NOT NULL,
    firmware_versao     VARCHAR(20),
    ultimo_contato      TIMESTAMP WITH TIME ZONE,
    bateria             DOUBLE PRECISION,
    produto_id          BIGINT REFERENCES produtos (id) ON DELETE SET NULL,
    capacidade_kg       NUMERIC(14, 2)
);

CREATE TABLE leituras (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id    BIGINT NOT NULL REFERENCES dispositivos (id) ON DELETE CASCADE,
    medido_em         TIMESTAMP WITH TIME ZONE NOT NULL,
    recebido_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    temperatura       DOUBLE PRECISION,
    umidade_ar        DOUBLE PRECISION,
    umidade_solo      DOUBLE PRECISION,
    nivel_percentual  DOUBLE PRECISION,
    bateria           DOUBLE PRECISION,
    rssi              INTEGER,
    CONSTRAINT uk_leitura_dispositivo_instante UNIQUE (dispositivo_id, medido_em)
);

CREATE TABLE alertas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id  BIGINT       NOT NULL REFERENCES dispositivos (id) ON DELETE CASCADE,
    tipo            VARCHAR(30)  NOT NULL,
    severidade      VARCHAR(10)  NOT NULL,
    mensagem        VARCHAR(255) NOT NULL,
    valor           DOUBLE PRECISION,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    reconhecido     BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_alerta_aberto ON alertas (reconhecido, criado_em);
