-- Talhões georreferenciados: o polígono é guardado em GeoJSON (coordenadas [lon, lat]).
CREATE TABLE talhoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(20)    NOT NULL UNIQUE,
    nome        VARCHAR(120)   NOT NULL,
    geometria   TEXT,
    area_ha     NUMERIC(10, 2),
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION
);

-- Migra os talhões que existiam só como texto nas colheitas.
INSERT INTO talhoes (codigo, nome)
SELECT DISTINCT talhao, 'Talhão ' || talhao FROM colheitas;

ALTER TABLE colheitas ADD COLUMN talhao_id BIGINT REFERENCES talhoes (id);
UPDATE colheitas SET talhao_id = (SELECT t.id FROM talhoes t WHERE t.codigo = colheitas.talhao);
ALTER TABLE colheitas ALTER COLUMN talhao_id SET NOT NULL;
ALTER TABLE colheitas DROP COLUMN talhao;

-- Safra no padrão brasileiro (jul–jun): plantio em ago/2025 pertence à safra 2025/26.
ALTER TABLE colheitas ADD COLUMN safra VARCHAR(7);
UPDATE colheitas SET safra =
    CASE WHEN EXTRACT(MONTH FROM data_plantio) >= 7
         THEN CAST(EXTRACT(YEAR FROM data_plantio) AS VARCHAR(4)) || '/' ||
              LPAD(CAST(MOD(CAST(EXTRACT(YEAR FROM data_plantio) AS INTEGER) + 1, 100) AS VARCHAR(2)), 2, '0')
         ELSE CAST(CAST(EXTRACT(YEAR FROM data_plantio) AS INTEGER) - 1 AS VARCHAR(4)) || '/' ||
              LPAD(CAST(MOD(CAST(EXTRACT(YEAR FROM data_plantio) AS INTEGER), 100) AS VARCHAR(2)), 2, '0')
    END;
ALTER TABLE colheitas ALTER COLUMN safra SET NOT NULL;
CREATE INDEX idx_colheita_talhao_safra ON colheitas (talhao_id, safra);

-- Ciclo de vida mais preciso: "em andamento" passa a ser "em desenvolvimento" (lavoura plantada).
UPDATE colheitas SET status = 'EM_DESENVOLVIMENTO' WHERE status = 'EM_ANDAMENTO';
ALTER TABLE colheitas ADD COLUMN status_desde TIMESTAMP WITH TIME ZONE;
UPDATE colheitas SET status_desde = CURRENT_TIMESTAMP;
ALTER TABLE colheitas ALTER COLUMN status_desde SET NOT NULL;

-- Histórico de mudanças de status (manual ou disparada por dispositivo de campo).
CREATE TABLE colheita_eventos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colheita_id      BIGINT       NOT NULL REFERENCES colheitas (id) ON DELETE CASCADE,
    status_anterior  VARCHAR(20),
    status_novo      VARCHAR(20)  NOT NULL,
    origem           VARCHAR(15)  NOT NULL,
    responsavel      VARCHAR(120),
    observacao       VARCHAR(255),
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    ocorrido_em      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_evento_colheita ON colheita_eventos (colheita_id, ocorrido_em);

-- Rastreador de máquinas: posição e estado de operação em cada leitura.
ALTER TABLE leituras ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE leituras ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE leituras ADD COLUMN velocidade DOUBLE PRECISION;
ALTER TABLE leituras ADD COLUMN operando BOOLEAN;

ALTER TABLE dispositivos ADD COLUMN veiculo_id BIGINT REFERENCES veiculos (id) ON DELETE SET NULL;
