-- Equipe de campo: operadores, máquinas que cada um pode operar e alocações em atividades.
CREATE TABLE operadores (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula        VARCHAR(20)  NOT NULL UNIQUE,
    nome             VARCHAR(120) NOT NULL,
    funcao           VARCHAR(30)  NOT NULL,
    turno            VARCHAR(15)  NOT NULL,
    cnh_categoria    VARCHAR(5),
    ausente_ate      DATE,
    motivo_ausencia  VARCHAR(120),
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE operador_habilitacoes (
    operador_id  BIGINT      NOT NULL REFERENCES operadores (id) ON DELETE CASCADE,
    tipo_veiculo VARCHAR(20) NOT NULL,
    PRIMARY KEY (operador_id, tipo_veiculo)
);

CREATE TABLE alocacoes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador_id    BIGINT       NOT NULL REFERENCES operadores (id) ON DELETE CASCADE,
    atividade      VARCHAR(20)  NOT NULL,
    veiculo_id     BIGINT REFERENCES veiculos (id) ON DELETE SET NULL,
    talhao_id      BIGINT REFERENCES talhoes (id) ON DELETE SET NULL,
    descricao      VARCHAR(255),
    inicio         TIMESTAMP WITH TIME ZONE NOT NULL,
    previsao_fim   TIMESTAMP WITH TIME ZONE,
    encerrada_em   TIMESTAMP WITH TIME ZONE,
    responsavel    VARCHAR(120),
    id_cliente     VARCHAR(36)  UNIQUE
);
CREATE INDEX idx_alocacao_operador_aberta ON alocacoes (operador_id, encerrada_em);
CREATE INDEX idx_alocacao_veiculo_aberta ON alocacoes (veiculo_id, encerrada_em);
