-- Várias fazendas por conta: cada registro passa a pertencer a uma fazenda (fazenda_id),
-- e usuários acessam as fazendas de que são membros.
CREATE TABLE fazendas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    municipio  VARCHAR(120) NOT NULL,
    uf         VARCHAR(2)   NOT NULL,
    latitude   DOUBLE PRECISION,
    longitude  DOUBLE PRECISION
);

CREATE TABLE usuario_fazendas (
    usuario_id  BIGINT NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    fazenda_id  BIGINT NOT NULL REFERENCES fazendas (id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, fazenda_id)
);

-- Bancos que já têm dados: tudo o que existe vira a "Fazenda principal", com acesso para todos.
INSERT INTO fazendas (nome, municipio, uf)
SELECT 'Fazenda principal', 'Não informado', 'PR'
WHERE EXISTS (SELECT 1 FROM usuarios) OR EXISTS (SELECT 1 FROM produtos) OR EXISTS (SELECT 1 FROM talhoes)
   OR EXISTS (SELECT 1 FROM veiculos) OR EXISTS (SELECT 1 FROM dispositivos) OR EXISTS (SELECT 1 FROM operadores);

INSERT INTO usuario_fazendas (usuario_id, fazenda_id)
SELECT u.id, f.id FROM usuarios u CROSS JOIN fazendas f;

ALTER TABLE produtos ADD COLUMN fazenda_id BIGINT;
UPDATE produtos SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE produtos ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE produtos ADD CONSTRAINT fk_produtos_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE movimentacoes_estoque ADD COLUMN fazenda_id BIGINT;
UPDATE movimentacoes_estoque SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE movimentacoes_estoque ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_movimentacoes_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;
CREATE INDEX idx_mov_fazenda_data ON movimentacoes_estoque (fazenda_id, ocorrido_em);

ALTER TABLE talhoes ADD COLUMN fazenda_id BIGINT;
UPDATE talhoes SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE talhoes ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE talhoes ADD CONSTRAINT fk_talhoes_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE colheitas ADD COLUMN fazenda_id BIGINT;
UPDATE colheitas SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE colheitas ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE colheitas ADD CONSTRAINT fk_colheitas_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;
CREATE INDEX idx_colheita_fazenda_safra ON colheitas (fazenda_id, safra);

ALTER TABLE colheita_eventos ADD COLUMN fazenda_id BIGINT;
UPDATE colheita_eventos SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE colheita_eventos ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE colheita_eventos ADD CONSTRAINT fk_eventos_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE veiculos ADD COLUMN fazenda_id BIGINT;
UPDATE veiculos SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE veiculos ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE veiculos ADD CONSTRAINT fk_veiculos_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE dispositivos ADD COLUMN fazenda_id BIGINT;
UPDATE dispositivos SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE dispositivos ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE dispositivos ADD CONSTRAINT fk_dispositivos_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE leituras ADD COLUMN fazenda_id BIGINT;
UPDATE leituras SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE leituras ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE leituras ADD CONSTRAINT fk_leituras_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE alertas ADD COLUMN fazenda_id BIGINT;
UPDATE alertas SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE alertas ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE alertas ADD CONSTRAINT fk_alertas_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;
CREATE INDEX idx_alerta_fazenda_aberto ON alertas (fazenda_id, reconhecido, criado_em);

ALTER TABLE operadores ADD COLUMN fazenda_id BIGINT;
UPDATE operadores SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE operadores ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE operadores ADD CONSTRAINT fk_operadores_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;

ALTER TABLE alocacoes ADD COLUMN fazenda_id BIGINT;
UPDATE alocacoes SET fazenda_id = (SELECT MIN(id) FROM fazendas);
ALTER TABLE alocacoes ALTER COLUMN fazenda_id SET NOT NULL;
ALTER TABLE alocacoes ADD CONSTRAINT fk_alocacoes_fazenda FOREIGN KEY (fazenda_id) REFERENCES fazendas (id) ON DELETE CASCADE;
